cityfact/config/routes.rb
Cityfact::Application.routes.draw do
  resources :cities
  root :to => "home#index"

end

cityfact/app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :title, :latitude, :longitude, :description, :dpu_team, :outputs, :related_outputs

  acts_as_gmappable :process_geocoding => false

  def gmaps4rails_infowindow
  	text="Title: #{self.title}<br>description: #{self.description}<br>dpu_team: #{self.dpu_team}"
  	if self.outputs.present?
  		text << "<br>outputs: #{self.outputs}"
  	end

  	if self.related_outputs.present?
  		text << "br>related_outputs: #{self.related_outputs}"
  	end

  	text
  end

end

cityfact/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

cityfact/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
    @cities_maps = City.all.to_gmaps4rails do |city, marker|
      marker.json "\"id\": #{city.id}"
    end




    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
end

cityfact/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index 
		@cities_maps = City.all.to_gmaps4rails do |city, marker|
      marker.json "\"id\": #{city.id}"
    end

	end

end

cityfact/app/helpers/application_helper.rb
module ApplicationHelper
end

cityfact/app/helpers/cities_helper.rb
module CitiesHelper
end

cityfact/app/helpers/index_helper.rb
module IndexHelper
end

cityfact/app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
    <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
    <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :dpu_team %><br />
    <%= f.text_field :dpu_team %>
  </div>
  <div class="field">
    <%= f.label :outputs %><br />
    <%= f.text_field :outputs %>
  </div>
  <div class="field">
    <%= f.label :related_outputs %><br />
    <%= f.text_field :related_outputs %>
  </div>
   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cityfact/app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

cityfact/app/views/cities/index.html.erb
<%= stylesheet_link_tag 'gmaps4rails' %>

<h1>Listing cities</h1>

<table class="table">

  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.title %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>

<%= gmaps4rails(@cities_maps) %> 

cityfact/app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

cityfact/app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @city.name %>
</p>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

cityfact/app/views/home/index.html.erb
<%= gmaps4rails(@cities_maps) %> 

cityfact/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cityfact</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<footer>
	 <%= yield :scripts %>
</footer>

</body>

</html>